name: Helm Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final_project_flask:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_flask:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Configure Kubernetes credentials
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy with Helm
      run: |
        helm upgrade --install final-project final-project-chart/ \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/final_project_flask \
          --set image.tag=${{ github.sha }} \
          --namespace default
